version: "3.7"

services:
  db:
    image: postgres:14.8
    container_name: "postgres"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_filename=postgresql.log"]
    environment:
      POSTGRES_USER: "postgres"  # Optional, but best to keep for consistency
      POSTGRES_HOST_AUTH_METHOD: "trust"  # Bypasses password authentication
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always  # Ensures it restarts if it fails

  redis:
    image: redis:7.0.8
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: ${REDIS_PORT}
        protocol: tcp
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    depends_on:
      - db

volumes:
  redis_data:
  pg_data:
